version: "3.8"
services:
  app:
    container_name: "${NAME}"
    image: "${NAME}"
    restart: always
    build:
      context: .
    volumes:
      - ./logs:/var/www/html/logs
    ports:
      - "${PORTS}"
    environment:
      DOMAIN: "${DOMAIN}"
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-group: "${AWS_LOG_GROUP}"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream: "support-time-elest.io/access.log"
  support-time-app-log:
    image: busybox
    volumes:
      - ./logs:/var/www/html/logs
    logging:
      driver: awslogs
      options:
        awslogs-group: "${AWS_LOG_GROUP}"
        awslogs-stream: "support-time-elest.io/app.log"
        awslogs-region: "${AWS_REGION}"
        awslogs-create-group: "true"
    command: tail -f /var/www/html/logs/app.log